import subprocess
import re

# Listing all users of the Windows system
def list_users():

    list_users_command = "net users"
    result = subprocess.run(list_users_command, shell=True, capture_output=True, text=True).stdout
    # print(result)

    # Extracting only usernames using regex patterns
    # Slicing is done to remove unnecessary ouput generated by 'net users' command
    usernames = re.findall(r"\b[A-Za-z]+\b", result)[4:-4]
    print(usernames)

# list_users()

# Adding user to 'Users' group
def add_user_to_group(username):
    
    add_user_to_group = f"net localgroup Users {username} /add"
    subprocess.run(add_user_to_group, shell=True, check=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
    print(f"{username} added to 'Users' group successfully")


# Removing user from 'Administrators' group
def remove_from_group(username):

    remove_user_from_group = f"net localgroup Administrators {username} /delete"
    subprocess.run(remove_user_from_group, shell=True, check=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
    print(f"{username} removed from 'Administrators' group successfully")


# Getting list of users
usernames = list_users()

# Asking user to enter the username from the list
username = input("Enter the username from the above list: ")

add_user_to_group(username)
remove_from_group(username)
